import { Developer, Startup } from "@/src/types";

export const mockDevelopers: Developer[] = [
  {
    id: "1",
    name: "Алексей Петров",
    rating: 4.8,
    projectsCount: 12,
    bio: "Full-stack разработчик с 8+ лет опыта",
  },
  {
    id: "2",
    name: "Мария Иванова",
    rating: 4.9,
    projectsCount: 8,
    bio: "Frontend-разработчик, специализируюсь на React и Next.js",
  },
  {
    id: "3",
    name: "Дмитрий Сидоров",
    rating: 4.7,
    projectsCount: 15,
    bio: "Mobile разработчик (iOS/Android), создаю качественные приложения",
  },
];

export const mockStartups: Startup[] = [
  {
    id: "1",
    title: "TaskFlow - Система управления задачами",
    shortDescription: "Современный таск-менеджер для команд с интеграциями",
    description:
      "TaskFlow - это мощная система управления проектами и задачами для команд любого размера. Включает канбан-доски, гант-диаграммы, отчёты и интеграции с популярными сервисами.",
    category: "saas",
    price: 500000,
    revenueShare: 40,
    features: [
      "Канбан-доски и списки задач",
      "Гант-диаграммы для планирования",
      "Система уведомлений и комментариев",
      "Интеграция с Telegram и Email",
      "Отчёты и аналитика",
      "API для интеграций",
      "Мобильная адаптация",
    ],
    techStack: ["Next.js", "TypeScript", "PostgreSQL", "Prisma", "TailwindCSS"],
    screenshots: ["/placeholder-1.jpg", "/placeholder-2.jpg"],
    demoUrl: "https://demo.taskflow.ru",
    developer: mockDevelopers[0],
    status: "active",
    views: 1250,
    likes: 89,
    createdAt: "2024-10-01",
    monthlyRevenue: 150000,
    users: 45,
  },
  {
    id: "2",
    title: "FitBot - Telegram бот для фитнеса",
    shortDescription: "Персональный тренер в Telegram с ИИ",
    description:
      "FitBot помогает пользователям достигать фитнес-целей через персонализированные тренировки, отслеживание прогресса и мотивационные уведомления. Использует ИИ для адаптации программ под пользователя.",
    category: "bot",
    price: 150000,
    revenueShare: 50,
    features: [
      "Персональные планы тренировок",
      "Отслеживание прогресса и веса",
      "Библиотека упражнений с видео",
      "Напоминания и мотивация",
      "Интеграция с фитнес-трекерами",
      "Чат с ИИ-тренером",
      "Статистика и графики",
    ],
    techStack: ["Node.js", "Telegraf", "MongoDB", "OpenAI API"],
    screenshots: ["/placeholder-3.jpg"],
    developer: mockDevelopers[1],
    status: "active",
    views: 890,
    likes: 67,
    createdAt: "2024-09-15",
    monthlyRevenue: 80000,
    users: 320,
  },
  {
    id: "3",
    title: "ShopTrack - Мобильное приложение для учёта покупок",
    shortDescription: "Умное приложение для контроля расходов",
    description:
      "ShopTrack помогает семьям и частным лицам контролировать расходы, планировать бюджет и находить лучшие предложения. Сканирование чеков, категоризация расходов, аналитика и многое другое.",
    category: "mobile",
    price: 800000,
    revenueShare: 35,
    features: [
      "Сканирование QR-кодов чеков",
      "Автоматическая категоризация",
      "Бюджетирование и лимиты",
      "Графики и отчёты",
      "Синхронизация между устройствами",
      "Экспорт данных",
      "Семейный доступ",
    ],
    techStack: ["React Native", "TypeScript", "Firebase", "Redux"],
    screenshots: ["/placeholder-4.jpg", "/placeholder-5.jpg"],
    developer: mockDevelopers[2],
    status: "active",
    views: 2100,
    likes: 143,
    createdAt: "2024-08-20",
    users: 0,
  },
  {
    id: "4",
    title: "ContentGen - Генератор контента для соцсетей",
    shortDescription: "ИИ-помощник для создания постов",
    description:
      "ContentGen использует нейросети для генерации текстов, хештегов и идей для контента. Поддерживает все популярные соцсети, имеет планировщик постов и аналитику.",
    category: "web",
    price: 350000,
    revenueShare: 45,
    features: [
      "Генерация текстов с помощью ИИ",
      "Подбор хештегов",
      "Планировщик публикаций",
      "Аналитика эффективности",
      "Шаблоны для разных ниш",
      "Интеграция с ВК, Instagram, Telegram",
      "Командная работа",
    ],
    techStack: ["Vue.js", "Python", "FastAPI", "PostgreSQL", "OpenAI"],
    screenshots: ["/placeholder-6.jpg"],
    demoUrl: "https://demo.contentgen.ru",
    developer: mockDevelopers[1],
    status: "active",
    views: 1560,
    likes: 112,
    createdAt: "2024-09-30",
    monthlyRevenue: 95000,
    users: 78,
  },
  {
    id: "5",
    title: "CRM Lite - Простая CRM для малого бизнеса",
    shortDescription: "Удобная CRM без лишних функций",
    description:
      "CRM Lite - это максимально простая и понятная система управления клиентами для малого бизнеса. Без сложных настроек, просто работает из коробки.",
    category: "saas",
    price: 600000,
    revenueShare: 40,
    features: [
      "База клиентов с историей",
      "Воронка продаж",
      "Задачи и напоминания",
      "Email-рассылки",
      "Отчёты по продажам",
      "Мобильное приложение",
      "Интеграция с мессенджерами",
    ],
    techStack: ["React", "Node.js", "MongoDB", "Express", "Material-UI"],
    screenshots: ["/placeholder-7.jpg", "/placeholder-8.jpg"],
    demoUrl: "https://demo.crmlite.ru",
    developer: mockDevelopers[0],
    status: "active",
    views: 980,
    likes: 73,
    createdAt: "2024-10-10",
    users: 0,
  },
  {
    id: "6",
    title: "LearnHub - Платформа для онлайн-курсов",
    shortDescription: "Готовая платформа для продажи курсов",
    description:
      "LearnHub - полнофункциональная платформа для создания и продажи онлайн-курсов. Включает видео-хостинг, тесты, сертификаты, интеграцию с платёжными системами.",
    category: "saas",
    price: 1200000,
    revenueShare: 30,
    features: [
      "Конструктор курсов",
      "Видео-плеер с защитой от скачивания",
      "Тесты и домашние задания",
      "Сертификаты об окончании",
      "Интеграция с ЮKassa и CloudPayments",
      "Личный кабинет студента",
      "Аналитика и отчёты",
      "Email-маркетинг",
    ],
    techStack: ["Next.js", "Node.js", "PostgreSQL", "AWS S3", "Stripe"],
    screenshots: ["/placeholder-9.jpg"],
    demoUrl: "https://demo.learnhub.ru",
    developer: mockDevelopers[2],
    status: "sold",
    views: 3200,
    likes: 210,
    createdAt: "2024-07-15",
    monthlyRevenue: 280000,
    users: 156,
  },
];
