import type { Metadata } from "next";

import QueryProvider from "@/src/lib/TanstackQueryProvider";
import { apiClient } from "@/src/lib/api-client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const me = await apiClient.api.auth.me.$get();
  console.log(await me.json());
  return (
    <>
      <QueryProvider>{children}</QueryProvider>
    </>
  );
}
