import type { Metadata } from "next";

import QueryProvider from "@/src/lib/TanstackQueryProvider";
import { apiClient } from "@/src/lib/api-client";
import { AuthInitializer } from "@/src/lib/AuthInitializer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <QueryProvider>
        <AuthInitializer />
        {children}
      </QueryProvider>
    </>
  );
}
